version: "3.8"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd project-0-0 && yarn start"
    ports:
      - "3000:3000"
